server {
    listen 5902;
    server_name _;

    root /usr/share/nginx/html/sidebar-crudstone/browser;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: API proxy to Quarkus
    location /api/ {
        proxy_pass http://pollanime-core-jvm:5555/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
